--- 
title: "Estadística Computacional"
author: "Teresa Ortiz"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
github-repo: tereom/est-computacional-2018
description: "Curso de estadística computacional, Maestría en Ciencia de Datos, ITAM 2018."
---

# Temario {-}


[Notas](https://tereom.github.io/est-computacional-2018/)

1. **Manipulación y visualización de datos**

-   Introducción a R.
-   Visualización de datos.
-   Manipulación y limpieza de datos.
-   Temas selectos de programación en R.

2. **Inferencia y remuestreo**

-   Repaso de probabilidad.
-   Muestreo y probabilidad.
-   Inferencia.
-   El principio del *plug-in*.
-   Bootstrap
    -   Cálculo de errores estándar e intervalos de confianza.
    -   Estructuras de datos complejos.
-   Introducción a modelos probabilísticos.

3. **Modelos de probabilidad y simulación**

-   Variables aleatorias y modelos probabilísticos.
-   Familias importantes: discretas y continuas.
-   Teoría básica de simulación
    -   El generador uniforme de números aleatorios.
    -   El método de la transformación inversa.
    -   Simulación de variables aleatorias discretas con soporte finito.
    -   Otras variables aleatorias.
-   Simulación para modelos gráficos
    -   Modelos probabilíticos gráficos.
    -   Simulación (e.g. ANOVA, regresión simple).
-   Inferencia paramétrica y remuestreo
    -   Modelos paramétricos.
    -   Bootsrap paramétrico.
-   Inferencia de gráficas

4. **Métodos computacionales e inferencia Bayesiana**

-   Inferencia bayesiana.
-   Métodos diretos
    -   Familias conjugadas.
    -   Aproximación por cuadrícula.
    -   Aceptación y rechazo.
-   MCMC
    -   Cadenas de Markov.
    -   Metropolis-Hastings.
    -   Muestreador de Gibbs.
    -   Diagnósticos de convergencia.

### Referencias {-}

[R for Data Science](http://r4ds.had.co.nz), Hadley Wickham, Garret Grolemund, O'Reilly.

[Advanced R](http://adv-r.had.co.nz/), Hadley Wickham, CRC Press.  
Simulation, Sheldon M. Ross, AP.  

A First Course in Probability, Sheldon M. Ross, Pearson.  

All of Statistics, A Concise Course in Statistical Inference, Larry Wasserman, Springer.  

An Introduction to the Bootstrap, Bradley Efron, Robert J. Tibshirani, Chapman & Hall.  

[Data Analysis Using Regression and Multilevel/Hierarchical Models](http://www.stat.columbia.edu/~gelman/arm/), Andrew Gelman, Jennifer Hill.  
[Doing Bayesian Data Analysis](https://sites.google.com/site/doingbayesiandataanalysis/), Second Edition, John K. Kruschke, AP.  

[Bayesian Data Analysis](http://www.stat.columbia.edu/~gelman/arm/), Andrew Gelman, John B. Carlin, Hal S. Stern and David B. Dunson.  

### Calificación {-}

Tareas 20% (se envían por correo con título: EstComp-TareaXX), exámen parcial (proyecto y exámen en clase) 40%, Exámen final 40%.

### Software {-}

- https://www.r-project.org
- https://www.rstudio.com